# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2019

variables:
  system.debug: true
  APPLICATION_NAME: 'sample-name'
  TENANTID: 'Your tenant id'
  APPLICATION_OWNERS: 'Email or User ObjectId'

steps:
- task: Set-Azure-AD-Application@4
  displayName: 'Set Azure AD Application'
  name: app
  inputs:
    azureSubscription: 'subscription name'
    createIfNotExist: true
    name: '$(APPLICATION_NAME)'
    signInAudience: 'AzureADMyOrg'
    appIdUri: 'https://$(TENANTID)/$(APPLICATION_NAME)'
    homePageUrl: 'https://YourHomePage.com'
    logoutUrl: 'https://YourLogoutUrl.com'
    termsOfServiceUrl: 'https://YourTermsUrl.com'
    privacyStatementUrl: 'https://YourPrivacyStatementUrl.com'
    multiTenant: false
    replyUrlsMethod: 'Multiline'
    replyUrlsMultiLine: 'https://YourReplyUrl.com'
    #resourceAccessFilePath: '$(Pipeline.Workspace)/drop/RequiredResourceAccess.json'
    #appRolesFilePath: '$(Pipeline.Workspace)/drop/AppRoles.json'
    ownersMethod: 'Singleline'
    ownersSingleLine: '$(APPLICATION_OWNERS)'
    secrets: '[{ ''Description'': ''testkey'', ''EndDate'': ''2023/12/16'' }]'
    oauth2AllowImplicitFlow: false
    appRoleAssignmentRequired: false

- powershell: |
    Write-Host "ObjectId- $(app.ObjectId)"
    Write-Host "ApplicationId- $(app.ApplicationId)"
    Write-Host "Name- $(app.Name)"
    Write-Host "AppIdUri- $(app.AppIdUri)"
    Write-Host "HomePageUrl- $(app.HomePageUrl)" 
    Write-Host "ServicePrincipalObjectId- $(app.ServicePrincipalObjectId)"
    Write-Host "The Secret with the name 'testkey'- $(app.Secret.testkey)"
  displayName: 'Print output variables'

- task: Remove-Azure-AD-Application@4
  displayName: 'Remove Azure AD Application'
  inputs:
    azureSubscription: 'subscription name'
    method: 'ObjectId'
    objectId: '$(app.ObjectId)'
